add ucorebook's proj1

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -1,4 +1,3 @@
-PROJ	:= challenge
 EMPTY	:=
 SPACE	:= $(EMPTY) $(EMPTY)
 SLASH	:= /
@@ -7,15 +6,15 @@ V       := @
 
 # try to infer the correct GCCPREFX
 ifndef GCCPREFIX
-GCCPREFIX := $(shell if i386-elf-objdump -i 2>&1 | grep '^elf32-i386$$' >/dev/null 2>&1; \
-	then echo 'i386-elf-'; \
+GCCPREFIX := $(shell if i386-ucore-elf-objdump -i 2>&1 | grep '^elf32-i386$$' >/dev/null 2>&1; \
+	then echo 'i386-ucore-elf-'; \
 	elif objdump -i 2>&1 | grep 'elf32-i386' >/dev/null 2>&1; \
 	then echo ''; \
 	else echo "***" 1>&2; \
-	echo "*** Error: Couldn't find an i386-elf version of GCC/binutils." 1>&2; \
-	echo "*** Is the directory with i386-elf-gcc in your PATH?" 1>&2; \
-	echo "*** If your i386-elf toolchain is installed with a command" 1>&2; \
-	echo "*** prefix other than 'i386-elf-', set your GCCPREFIX" 1>&2; \
+	echo "*** Error: Couldn't find an i386-ucore-elf version of GCC/binutils." 1>&2; \
+	echo "*** Is the directory with i386-ucore-elf-gcc in your PATH?" 1>&2; \
+	echo "*** If your i386-ucore-elf toolchain is installed with a command" 1>&2; \
+	echo "*** prefix other than 'i386-ucore-elf-', set your GCCPREFIX" 1>&2; \
 	echo "*** environment variable to that prefix and run 'make' again." 1>&2; \
 	echo "*** To turn off this error, run 'gmake GCCPREFIX= ...'." 1>&2; \
 	echo "***" 1>&2; exit 1; fi)
@@ -23,10 +22,10 @@ endif
 
 # try to infer the correct QEMU
 ifndef QEMU
-QEMU := $(shell if which qemu-system-i386 > /dev/null; \
-	then echo 'qemu-system-i386'; exit; \
-	elif which i386-elf-qemu > /dev/null; \
-	then echo 'i386-elf-qemu'; exit; \
+QEMU := $(shell if which qemu > /dev/null; \
+	then echo 'qemu'; exit; \
+	elif which i386-ucore-elf-qemu > /dev/null; \
+	then echo 'i386-ucore-elf-qemu'; exit; \
 	else \
 	echo "***" 1>&2; \
 	echo "*** Error: Couldn't find a working QEMU executable." 1>&2; \
@@ -45,14 +44,15 @@ endif
 HOSTCC		:= gcc
 HOSTCFLAGS	:= -g -Wall -O2
 
+GDB		:= $(GCCPREFIX)gdb
+
 CC		:= $(GCCPREFIX)gcc
-CFLAGS	:= -fno-builtin -Wall -ggdb -m32 -gstabs -nostdinc $(DEFS)
+CFLAGS	:= -fno-builtin -Wall -ggdb -m32 -nostdinc
 CFLAGS	+= $(shell $(CC) -fno-stack-protector -E -x c /dev/null >/dev/null 2>&1 && echo -fno-stack-protector)
 CTYPE	:= c S
 
 LD      := $(GCCPREFIX)ld
 LDFLAGS	:= -m $(shell $(LD) -V | grep elf_i386 2>/dev/null)
-LDFLAGS	+= -nostdlib
 
 OBJCOPY := $(GCCPREFIX)objcopy
 OBJDUMP := $(GCCPREFIX)objdump
@@ -61,11 +61,6 @@ COPY	:= cp
 MKDIR   := mkdir -p
 MV		:= mv
 RM		:= rm -f
-AWK		:= awk
-SED		:= sed
-SH		:= sh
-TR		:= tr
-TOUCH	:= touch -c
 
 OBJDIR	:= obj
 BINDIR	:= bin
@@ -92,53 +87,11 @@ asmfile = $(call cgtype,$(call toobj,$(1)),o,asm)
 outfile = $(call cgtype,$(call toobj,$(1)),o,out)
 symfile = $(call cgtype,$(call toobj,$(1)),o,sym)
 
-# for match pattern
-match = $(shell echo $(2) | $(AWK) '{for(i=1;i<=NF;i++){if(match("$(1)","^"$$(i)"$$")){exit 1;}}}'; echo $$?)
-
 # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-# include kernel/user
 
-# INCLUDE	+= libs/
+INCLUDE	+= libs/
 
-# CFLAGS	+= $(addprefix -I,$(INCLUDE))
-
-# LIBDIR	+= libs
-
-# $(call add_files_cc,$(call listf_cc,$(LIBDIR)),libs,)
-
-# # -------------------------------------------------------------------
-# # kernel
-
-# KINCLUDE	+= kern/debug/ \
-# 			   kern/driver/ \
-# 			   kern/trap/ \
-# 			   kern/mm/
-
-# KSRCDIR		+= kern/init \
-# 			   kern/libs \
-# 			   kern/debug \
-# 			   kern/driver \
-# 			   kern/trap \
-# 			   kern/mm
-
-# KCFLAGS		+= $(addprefix -I,$(KINCLUDE))
-
-# $(call add_files_cc,$(call listf_cc,$(KSRCDIR)),kernel,$(KCFLAGS))
-
-# KOBJS	= $(call read_packet,kernel libs)
-
-# # create kernel target
-# kernel = $(call totarget,kernel)
-
-# $(kernel): tools/kernel.ld
-
-# $(kernel): $(KOBJS)
-# 	@echo + ld $@
-# 	$(V)$(LD) $(LDFLAGS) -T tools/kernel.ld -o $@ $(KOBJS)
-# 	@$(OBJDUMP) -S $@ > $(call asmfile,kernel)
-# 	@$(OBJDUMP) -t $@ | $(SED) '1,/SYMBOL TABLE/d; s/ .* / /; /^$$/d' > $(call symfile,kernel)
-
-# $(call create_target,kernel)
+CFLAGS	+= $(addprefix -I,$(INCLUDE))
 
 # -------------------------------------------------------------------
 
@@ -148,11 +101,10 @@ $(foreach f,$(bootfiles),$(call cc_compile,$(f),$(CC),$(CFLAGS) -Os -nostdinc))
 
 bootblock = $(call totarget,bootblock)
 
-$(bootblock): $(call toobj,$(bootfiles)) | $(call totarget,sign)
+$(bootblock): $(call toobj,boot/bootasm.S) $(call toobj,$(bootfiles)) | $(call totarget,sign)
 	@echo + ld $@
 	$(V)$(LD) $(LDFLAGS) -N -e start -Ttext 0x7C00 $^ -o $(call toobj,bootblock)
 	@$(OBJDUMP) -S $(call objfile,bootblock) > $(call asmfile,bootblock)
-	@$(OBJDUMP) -t $(call objfile,bootblock) | $(SED) '1,/SYMBOL TABLE/d; s/ .* / /; /^$$/d' > $(call symfile,bootblock)
 	@$(OBJCOPY) -S -O binary $(call objfile,bootblock) $(call outfile,bootblock)
 	@$(call totarget,sign) $(call outfile,bootblock) $(bootblock)
 
@@ -167,98 +119,46 @@ $(call create_target_host,sign,sign)
 # -------------------------------------------------------------------
 
 # create ucore.img
-# UCOREIMG	:= $(call totarget,ucore.img)
+UCOREIMG	:= $(call totarget,ucore.img)
 
-# $(UCOREIMG): $(kernel) $(bootblock)
-# 	$(V)dd if=/dev/zero of=$@ count=10000
-# 	$(V)dd if=$(bootblock) of=$@ conv=notrunc
-# 	$(V)dd if=$(kernel) of=$@ seek=1 conv=notrunc
+$(UCOREIMG): $(call totarget,bootblock)
+	$(V)dd if=/dev/zero of=$@ count=10000
+	$(V)dd if=$< of=$@ conv=notrunc
 
-# $(call create_target,ucore.img)
+$(call create_target,ucore.img)
 
 # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 
 $(call finish_all)
 
-# IGNORE_ALLDEPS	= clean \
-# 				  dist-clean \
-# 				  grade \
-# 				  touch \
-# 				  print-.+ \
-# 				  handin
-
-# ifeq ($(call match,$(MAKECMDGOALS),$(IGNORE_ALLDEPS)),0)
-# -include $(ALLDEPS)
-# endif
-
-# files for grade script
+ifneq ($(MAKECMDGOALS),clean)
+-include $(ALLDEPS)
+endif
 
 TARGETS: $(TARGETS)
-all: $(TARGETS)
+
 .DEFAULT_GOAL := TARGETS
 
-# .PHONY: qemu qemu-nox debug debug-nox
-# lab1-mon: $(UCOREIMG)
-# 	$(V)$(TERMINAL) -e "$(QEMU) -S -s -d in_asm -D $(BINDIR)/q.log -monitor stdio -hda $< -serial null"
-# 	$(V)sleep 2
-# 	$(V)$(TERMINAL) -e "gdb -q -x tools/lab1init"
-# debug-mon: $(UCOREIMG)
-# #	$(V)$(QEMU) -S -s -monitor stdio -hda $< -serial null &
-# 	$(V)$(TERMINAL) -e "$(QEMU) -S -s -monitor stdio -hda $< -serial null"
-# 	$(V)sleep 2
-# 	$(V)$(TERMINAL) -e "gdb -q -x tools/moninit"
-# qemu-mon: $(UCOREIMG)
-# 	$(V)$(QEMU) -monitor stdio -hda $< -serial null
-# qemu: $(UCOREIMG)
-# 	$(V)$(QEMU) -parallel stdio -hda $< -serial null
+.PHONY: qemu qemu-nox debug debug-nox
+qemu: $(UCOREIMG)
+	$(V)$(QEMU) -parallel stdio -hda $< -serial null
 
-# qemu-nox: $(UCOREIMG)
-# 	$(V)$(QEMU) -serial mon:stdio -hda $< -nographic
-# TERMINAL        :=gnome-terminal
-# gdb: $(UCOREIMG)
-# 	$(V)$(QEMU) -S -s -parallel stdio -hda $< -serial null
-# debug: $(UCOREIMG)
-# 	$(V)$(QEMU) -S -s -parallel stdio -hda $< -serial null &
-# 	$(V)sleep 2
-# 	$(V)$(TERMINAL)  -e "cgdb -q -x tools/gdbinit"
-	
-# debug-nox: $(UCOREIMG)
-# 	$(V)$(QEMU) -S -s -serial mon:stdio -hda $< -nographic &
-# 	$(V)sleep 2
-# 	$(V)$(TERMINAL) -e "gdb -q -x tools/gdbinit"
+qemu-nox: $(UCOREIMG)
+	$(V)$(QEMU) -serial mon:stdio -hda $< -nographic
 
-# .PHONY: grade touch
+TERMINAL := gnome-terminal
 
-# GRADE_GDB_IN	:= .gdb.in
-# GRADE_QEMU_OUT	:= .qemu.out
-# HANDIN			:= proj$(PROJ)-handin.tar.gz
+debug: $(UCOREIMG)
+	$(V)$(QEMU) -S -s -parallel stdio -hda $< -serial null &
+	$(V)sleep 2
+	$(V)$(TERMINAL) -e "$(GDB) -q -x tools/gdbinit"
 
-# TOUCH_FILES		:= kern/trap/trap.c
+debug-nox: $(UCOREIMG)
+	$(V)$(QEMU) -S -s -serial mon:stdio -hda $< -nographic &
+	$(V)sleep 2
+	$(V)$(TERMINAL) -e "$(GDB) -q -x tools/gdbinit"
 
-# MAKEOPTS		:= --quiet --no-print-directory
-
-# grade:
-# 	$(V)$(MAKE) $(MAKEOPTS) clean
-# 	$(V)$(SH) tools/grade.sh
-
-# touch:
-# 	$(V)$(foreach f,$(TOUCH_FILES),$(TOUCH) $(f))
-
-# print-%:
-# 	@echo $($(shell echo $(patsubst print-%,%,$@) | $(TR) [a-z] [A-Z]))
-
-.PHONY: clean dist-clean handin packall
+.PHONY: clean
 clean:
-	$(V)$(RM) $(GRADE_GDB_IN) $(GRADE_QEMU_OUT)
 	-$(RM) -r $(OBJDIR) $(BINDIR)
-
-dist-clean: clean
-	-$(RM) $(HANDIN)
-
-handin: packall
-	@echo Please visit http://learn.tsinghua.edu.cn and upload $(HANDIN). Thanks!
-
-packall: clean
-	@$(RM) -f $(HANDIN)
-	@tar -czf $(HANDIN) `find . -type f -o -type d | grep -v '^\.*$$' | grep -vF '$(HANDIN)'`
 
